using System;
using System.Collections.Generic;

namespace ES_POS_BUSY.Services.DBContext;

public partial class Tran1
{
    public int VchCode { get; set; }

    public short VchType { get; set; }

    public DateTime Date { get; set; }

    public DateTime StockUpdationDate { get; set; }

    public short Status { get; set; }

    public string VchNo { get; set; } = null!;

    public int VchSeriesCode { get; set; }

    public int MasterCode1 { get; set; }

    public int MasterCode2 { get; set; }

    public int Stamp { get; set; }

    public int AutoVchNo { get; set; }

    public int Cm1 { get; set; }

    public int Cm2 { get; set; }

    public int Cm3 { get; set; }

    public int Cm4 { get; set; }

    public int Cm5 { get; set; }

    public int Cm6 { get; set; }

    public double FormRecAmt { get; set; }

    public double FormIssAmt { get; set; }

    public double CurConRate { get; set; }

    public double VchAmtBaseCur { get; set; }

    public double VchSalePurcAmt { get; set; }

    public bool ExciseApplicable { get; set; }

    public string ExciseDocName { get; set; } = null!;

    public double ExciseValue { get; set; }

    public short ExciseType { get; set; }

    public double ExcisableAmount { get; set; }

    public double ExciseRate { get; set; }

    public double OrgVchAmtBaseCur { get; set; }

    public bool Teapplicable { get; set; }

    public bool Tdsapplicable { get; set; }

    public short FormRecStatus { get; set; }

    public short FormIssStatus { get; set; }

    public short ChallanStatus { get; set; }

    public bool Stapplicable { get; set; }

    public short Sttype { get; set; }

    public bool DocPrinted { get; set; }

    public bool External { get; set; }

    public string CreatedBy { get; set; } = null!;

    public DateTime CreationTime { get; set; }

    public string AuthorisedBy { get; set; } = null!;

    public DateTime AuthorisationTime { get; set; }

    public string ModifiedBy { get; set; } = null!;

    public DateTime ModificationTime { get; set; }

    public short PriceCategory { get; set; }

    public bool Vatinfo { get; set; }

    public bool Posenabled { get; set; }

    public short AutoGeneratedType { get; set; }

    public bool VchCancelled { get; set; }

    public short BrokerageMode { get; set; }

    public double Brokerage { get; set; }

    public double BrokerageAmt { get; set; }

    public short TranType { get; set; }

    public bool FreeQtyUsed { get; set; }

    public bool Cancelled { get; set; }

    public double D1 { get; set; }

    public short ApprovalStatus { get; set; }

    public bool SyncStatus { get; set; }

    public short Source { get; set; }

    public short AuditStatus { get; set; }

    public double ExtraExpense { get; set; }

    public string ExtraExpenseNar1 { get; set; } = null!;

    public string ExtraExpenseNar2 { get; set; } = null!;

    public string C1 { get; set; } = null!;

    public DateTime Date1 { get; set; }

    public DateTime Date2 { get; set; }

    public short I1 { get; set; }

    public short I2 { get; set; }

    public short I3 { get; set; }

    public short I4 { get; set; }

    public short I5 { get; set; }

    public short I6 { get; set; }

    public short I7 { get; set; }

    public short I8 { get; set; }

    public short I9 { get; set; }

    public short I10 { get; set; }

    public bool B1 { get; set; }

    public bool Tpf1 { get; set; }

    public bool Tpf2 { get; set; }

    public short RejectionStatus { get; set; }

    public int L1 { get; set; }

    public string SourceDet { get; set; } = null!;

    public string NepaliDate { get; set; } = null!;

    public string NepaliFy { get; set; } = null!;

    public int Cm7 { get; set; }

    public bool Tcsapplicable { get; set; }

    public short ReturnStatus { get; set; }

    public short ReturnStatusAnnual { get; set; }

    public bool Gstinfo { get; set; }

    public short GstrecType { get; set; }

    public short InputType { get; set; }

    public short GstrepBasis { get; set; }

    public short Gstr2status { get; set; }

    public string CheckSum { get; set; } = null!;

    public bool SyncWithIrd { get; set; }

    public bool IsRealtime { get; set; }

    public short ConsignmentType { get; set; }

    public short ItcclaimedStatus { get; set; }

    public short ItcclaimedMonth { get; set; }

    public string EinvIrn { get; set; } = null!;

    public string EinvAckNo { get; set; } = null!;

    public DateTime EinvAckDate { get; set; }

    public string EinvSignedQrcode { get; set; } = null!;

    public string EinvSignedInvoice { get; set; } = null!;

    public string EinvSignedInvoice2 { get; set; } = null!;

    public string EinvSignedInvoice3 { get; set; } = null!;

    public string EinvSignedInvoice4 { get; set; } = null!;

    public string EinvSignedInvoice5 { get; set; } = null!;

    public string SelfImageLink { get; set; } = null!;

    public string BusyDocLink { get; set; } = null!;

    public string SelfImageName { get; set; } = null!;

    public string BusyDocName { get; set; } = null!;

    public short Gstr2bstatus { get; set; }

    public short Gstr2bmonth { get; set; }

    public short Gstr2byear { get; set; }

    public string OldIdentity { get; set; } = null!;
}
